// <auto-generated />
namespace Migrations.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class InterceptorTest1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InterceptorTest1));
        
        string IMigrationMetadata.Id
        {
            get { return "202408200909207_InterceptorTest1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
