// <auto-generated />
namespace Migrations.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Add_DBChangeTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_DBChangeTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202408160915065_Add_DBChangeTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
